### PR TITLE
Meter supports overriding m1Rate, m5Rate & m15Rate via properties

### PR DESCRIPTION
**Pull request by hugebdu**
@felixge The same idea you [have](https://github.com/felixge/node-measured/blob/master/lib/metrics/Histogram.js#L8) already in `Histogram`, but for `Meter`.

### CODE REVIEW

**Comment by hugebdu** [comment]
cc @viliusl

**Comment by felixge** [comment]
@hugebdu thx.

**Comment by hugebdu** [comment]
Thank you!

**Comment by hugebdu** [comment]
@felixge any plans for releasing my change? :)

**Comment by felixge** [comment]
@hugebdu no, but if you give me your npm username I'm happy to give you permissions to push the release yourself :)

**Comment by hugebdu** [comment]
`hugebdu` that is.

10x!

**Comment by felixge** [comment]
@hugebdu done! You should be able to npm publish. Also added you on GH.

**Pull request merged**
